version: "3.5"

services:
  server:
    image: ghcr.io/animo/funke-wallet-provider/server:main
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        traefik.enable: "true"

        traefik.http.routers.funke-wallet-service-provider.rule: Host(`wsp.funke.animo.id`)
        traefik.http.routers.funke-wallet-service-provider.entrypoints: web-secure
        traefik.http.routers.funke-wallet-service-provider.tls.certresolver: zerossl
        traefik.http.routers.funke-wallet-service-provider.service: funke-wallet-service-provider-service
        traefik.http.services.funke-wallet-service-provider-service.loadbalancer.server.port: 3000

    networks:
      - traefik

    ports:
      - "3000"

networks:
  traefik:
    external: true
    name: traefik
